# Generated by Django 3.1.6 on 2021-05-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20210519_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reg',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reg',
            name='usertype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
