# Generated by Django 3.1.6 on 2021-05-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20210519_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('age', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
