# Generated by Django 3.1.6 on 2021-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_att'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='aadhar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mem',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mem',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
