# Generated by Django 3.1.6 on 2021-05-28 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20210525_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.CharField(default='', max_length=100)),
                ('loan_type', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('rg1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.mem')),
            ],
        ),
    ]
