# Generated by Django 3.1.6 on 2021-05-31 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='repay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('r_amount', models.CharField(default='', max_length=100)),
                ('rg1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.loan')),
            ],
        ),
    ]
