# Generated by Django 3.1.6 on 2021-06-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_repay'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='b_amount',
            field=models.CharField(default='', max_length=100),
        ),
    ]
