# Generated by Django 3.1.6 on 2021-06-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_loan_b_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
